### ISSUE TITLE
Search in Item Lookup page isn't working

### ISSUE THREAD

**Issue by khairulhaaziq** [dosm-malaysia/aksara-front#102]
Search for table in Item Lookup page doesn't work. I tried with other pages, seems to work fine.

<img width="1092" alt="Screenshot 2023-01-30 at 9 46 55 PM" src="https://user-images.githubusercontent.com/101852870/215495200-d1391fbe-8b9d-4707-8a04-4bd1b7928c77.png">

<img width="993" alt="Screenshot 2023-01-30 at 9 47 10 PM" src="https://user-images.githubusercontent.com/101852870/215495278-21584aaa-8776-4712-ab76-1cea43380685.png">

Also, the table appears incomplete. Is it intended as such?

**Comment by irfancoder** [comment]
Hi @khairulhaaziq, thanks for letting us know about the bug. 

Made a note and we will improve on the existing table search. About the table 'appearing incomplete', can you tell us what you mean by that?

**Comment by khairulhaaziq** [comment]
>  About the table 'appearing incomplete', can you tell us what you mean by that?

The table is incomplete. For example, on [the item lookup page](https://open.dosm.gov.my/data-catalogue/dosm-public-pricecatcher_lookup_item_preview_0), the table has 120 rows, while the downloadable CSV has 757 rows, same for [the premise lookup page](https://open.dosm.gov.my/data-catalogue/dosm-public-pricecatcher_lookup_premise_preview_0), it only has 120 rows. Do you guys limit it for some reason?

**Comment by irfancoder** [comment]
23d61ca08e641288a48f725abeb117078d751262 - The table search bug is now fixed and currently on staging.

Regarding the incomplete table, the data team has purposely limited the number of rows to be displayed on site for now. They will rollout the rest once they are ready. Thank you
