### ISSUE TITLE
Add a language choice dialog for first-time users

### ISSUE THREAD

**Issue by iskandarzhilmi** [dosm-malaysia/aksara-front#127]
As OpenDOSM is a platform that deals with Malaysia's data and is associated with the government, the default language being English might not be suitable for all users. To improve user experience and cater to a broader Malaysian audience, we need to prompt first-time users to choose their preferred language, either Bahasa Melayu or English, similar to the [Shopee](http://shopee.com.my) website.

I propose adding a dialog box that appears when a first-time user visits the website. This dialog box should be multilingual and provide the user with an option to choose between Bahasa Melayu and English as their preferred language. The chosen language should then be saved.

**Comment by Fe1777** [comment]
## Implementing First-Visit Language Selection

Here's a guide to implement a language selection dialog that appears on a user's first visit. This dialog will allow users to choose their preferred language, save the selection in local storage, and apply the choice automatically on future visits.

### Step 1: Create Language Selection Modal

First, we'll create a new component for our language selection modal. Assuming we're using React, make sure to have `react` and `react-modal` installed:

```bash
npm install react-modal
```

Now, let's create a new file `LanguageSelectionModal.js` for our modal component:

```javascript
import React, { useState } from 'react';
import Modal from 'react-modal';

const LanguageSelectionModal = ({ isOpen, onClose, onSelectLanguage }) => {
  const languages = ['English', 'Malay', 'Chinese', 'Tamil']; // Supported languages

  const handleLanguageSelect = (language) => {
    onSelectLanguage(language);
    onClose();
  };

  return (
    <Modal
      isOpen={isOpen}
      onRequestClose={onClose}
      contentLabel="Select Your Preferred Language"
    >
      <h2>Select Your Preferred Language</h2>
      <ul>
        {languages.map((language) => (
          <li key={language}>
            <button onClick={() => handleLanguageSelect(language)}>{language}</button>
          </li>
        ))}
      </ul>
    </Modal>
  );
};

export default LanguageSelectionModal;
```

### Step 2: Manage Language Selection

We'll now integrate this modal into our main application component. We'll manage the modal's state and handle the user's language selection.

In your main application component (e.g., `App.js`), do the following:

```javascript
import React, { useState, useEffect } from 'react';
import LanguageSelectionModal from './LanguageSelectionModal';

const App = () => {
  const [isLanguageModalOpen, setIsLanguageModalOpen] = useState(false);
  const [language, setLanguage] = useState('');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('preferredLanguage');
    if (!savedLanguage) {
      setIsLanguageModalOpen(true);
    } else {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleLanguageSelect = (selectedLanguage) => {
    setLanguage(selectedLanguage);
    localStorage.setItem('preferredLanguage', selectedLanguage);
    setIsLanguageModalOpen(false);
  };

  return (
    <div>
      <LanguageSelectionModal
        isOpen={isLanguageModalOpen}
        onClose={() => setIsLanguageModalOpen(false)}
        onSelectLanguage={handleLanguageSelect}
      />
      <h1>Welcome to the Site</h1>
      {language && <p>Your preferred language is: {language}</p>}
    </div>
  );
};

export default App;
```

### Step 3: Style and Configurations

Next, make sure your modal looks good. Add any necessary styles to make the modal user-friendly.

You can add global styles or modal-specific CSS classes in a `styles.css` file:

```css
/* Add global styles or modal-specific styles */
```

Configure the `Modal` base styles, if needed:

```javascript
Modal.setAppElement('#root'); // Ensures screen readers work correctly by setting the root element
```

### Step 4: Test Your Implementation

- Run your application: `npm start`
- Open the app in your browser.
- Clear local storage to simulate a first-time visit: `localStorage.clear();`
- Refresh the page and check if the language selection modal appears.
- Select a language and verify it saves and applies automatically on future visits.

### Additional Touches

- Add styles to make the modal more visually appealing.
- Consider using flags/icons for better language recognition.
- Ensure accessibility features like keyboard navigation and screen reader support are in place.

By following these steps, you'll have a functional, user-friendly language selection dialog that appears on the first visit, improving the overall user experience and accessibility.

**Comment by dosm-malaysia** [comment]
This looks like ChatGPT generated content. 

Furthermore, this project is no longer actively maintained - as we have migrated and integrated with datagovmy. See [here](https://github.com/data-gov-my/datagovmy-front/tree/main/apps/opendosm).
