### ISSUE TITLE
Slider start and end knob bugged

### ISSUE THREAD

**Issue by Jy411** [dosm-malaysia/aksara-front#128]
https://open.dosm.gov.my/data-catalogue/dosm-public-economy_gdp_2

The start and end knob of the graphs slider is bugged, you can drag the end knob to a position before the start knob. For example:

Before:
![image](https://user-images.githubusercontent.com/19220040/232681660-bd9851dd-02be-4d23-bd1e-6f3ffccb6c92.png)

After:
![image](https://user-images.githubusercontent.com/19220040/232681735-72c44339-3113-4963-9e6a-c259ef6f9d25.png)

**Comment by 1axmansharma** [comment]
@irfancoder Is this issue resolved ? If not I would like to contribute.

**Comment by irfancoder** [comment]
Hi @1axmansharma, this version of OpenDOSM is no longer in active service and the project has been migrated into [datagovmy-front](https://github.com/data-gov-my/datagovmy-front) as part of the bigger data monorepo. Goes without saying, the slider bug has been fixed there. 

As for this repo, it will be publicly archived soon. You are more than welcome to contribute at [datagovmy-front](https://github.com/data-gov-my/datagovmy-front) instead! Be sure to check the Issues & Discussions to see how you can contribute
